apiVersion: v1
kind: Service
metadata:
  name: healthcare-frontend-service
spec:
  selector:
    app: healthcare-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
