apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genai-rag-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
    - host: YOUR_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genai-rag-service
                port:
                  number: 80
